name: E2E Tests
on:
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  e2e:
    name: Cypress E2E Suite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Run E2E suite
        run: yarn e2e:replay
        env:
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.7
        with:
          api-key: rwk_tuo6kepOi7xI7oOFJzylf2GNqql3CMOgeCsGtAwuyhf
